### ISSUE TITLE
Beacon 인식 문제 (ar 페이지)

### ISSUE THREAD

**Issue by JooSeuYoon** [capston03/capstone-project-front#20]
ar.dart에서 beaconList 불러올 때 어떤 비콘도 인식되지 않음
beacon.dart에서 getBeaconList getter 사용, constructor 에서 initBeacon과 scan 이후 getBeaconList를 불러오는 상황
dialog에 beacon name이 뜨지 않음을 확인

**Comment by namhyo01** [comment]
This issue is not doing because plan is changed
